# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae0eb856e24be952e4918313556612d5544330af01e52598f2c979b11d122e57f060752d49a449fb1fb7814dd56682934133efecc4c1fe0a9c621be3d43318b5

test:
  secret_key_base: 245b1e2e7780cfd9c9dd592312f3de33a36218a0cead80f963a06aaacffb6cbbafe57fbe7c3f0fa12e09f710302036e8f4fbea4f3aa16f03677c70d9e9525e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
